import Image from 'next/image'; import Link from 'next/link'; import {ArrowRight, Phone} from 'lucide-react'; import {services,wa,emergencyPhone} from '@/lib/data'; import Counter from '@/components/Counter';

const serviceImages:Record<string,string>={'car-rental':'/images/car-rental.jpg','vehicle-importation':'/images/vehicle-import.jpg','distribution':'/images/hero-fleet.jpg','staff-bussing':'/images/staff-bussing.jpg','private-vip-drive':'/images/vip-transport.jpg'};
const ticker=['VIP transport','24/7 Emergency & escort','Car rentals','Logistics','Private hire driver','Car importation','Staff bussing'];

export default function Home(){return <main>
<section className="heroF"><video className="heroF-bg" autoPlay muted loop playsInline preload="auto" poster="/images/hero-fleet.jpg" aria-label="Avar Logistics fleet, vehicle importation, VIP transport and port operations"><source src="/videos/hero-loop.mp4" type="video/mp4"/></video><div className="heroF-overlay"/><div className="container heroF-inner"><div className="eyebrow" style={{color:'#ffb3a1'}}>Avar Logistics Africa · Ghana & West Africa</div><h1 className="display heroF-title">IMPORTS, RENTALS, AND<br/><em>VIP TRANSPORT.</em></h1><p>One accountable partner for vehicle importation, car rentals, goods distribution, staff bussing and executive movement — planned with discipline, executed with safety at the centre.</p><div className="heroF-actions"><Link className="btn btn-primary" href="/contact">GET A QUOTE <ArrowRight size={16}/></Link><Link className="heroF-alt" href="/partnerships">BECOME AN AVAR PARTNER<i/></Link></div></div>
<div className="marquee"><div className="marquee-track">{[...ticker,...ticker,...ticker,...ticker].map((t,i)=><span key={i}>{t}<b>◆</b></span>)}</div></div></section>

<section className="section whowe"><div className="container whowe-grid"><div className="whowe-media"><Image src="/images/team-fleet.jpg" alt="Avar drivers and coordinators with the company fleet in Accra" width={880} height={660}/><i className="whowe-frame"/></div><div className="whowe-copy"><h6 className="mini-head">WHO WE ARE</h6><h2 className="display">A GHANAIAN LOGISTICS PARTNER BUILT ON DISCIPLINE.</h2><p>Avar Logistics Africa Ltd is a Ghanaian-owned transport and logistics company serving organisations and individuals across Ghana and the West African sub-region. We bring vehicle importation, car rentals, goods distribution, staff bussing and private/VIP transport under one professional standard.</p><p>Fewer hand-offs. Clearer accountability. A team that communicates early, plans routes responsibly and treats every movement — from a single rental to an enterprise shuttle programme — with the same safety-led care.</p><Link className="btn btn-dark" href="/about">LEARN MORE <ArrowRight size={16}/></Link></div></div></section>

<section className="section whatwedo"><div className="container"><h2 className="display center-head">WHAT WE DO</h2><div className="wedo-grid">{services.map(s=><Link key={s.slug} href={`/services/${s.slug}`} className="wedo-card"><div className="wedo-img"><Image src={serviceImages[s.slug]||s.image} alt={s.title} fill sizes="(max-width:850px) 50vw, 25vw"/></div><span>{s.title}</span></Link>)}<Link href="/emergency-escort" className="wedo-card wedo-hot"><div className="wedo-img"><Image src="/images/vip-transport.jpg" alt="Emergency and escort coordination" fill sizes="(max-width:850px) 50vw, 25vw"/></div><span><b className="pulse"/>Emergency & Escort</span></Link></div></div></section>

<section className="spotlight"><div className="container spotlight-inner"><h6 className="mini-head" style={{color:'#ff8b72'}}>SIGNATURE SERVICE</h6><h2 className="display">THE EMERGENCY & ESCORT DESK</h2><i className="spot-rule"/><p>When movement becomes urgent — a medical run, a high-value vehicle movement, a principal who must arrive on time — you speak directly with a response coordinator, not a generic inbox. We coordinate emergency transport, arrange police escort support for approved movements, and can document the journey on video for your records.</p><div className="spotlight-actions"><a className="btn btn-primary" href={`tel:${emergencyPhone}`}><Phone size={16}/> {emergencyPhone}</a><Link className="heroF-alt" href="/emergency-escort">HOW THE ESCORT DESK WORKS<i/></Link></div></div></section>

<section className="stats"><div className="container stats-grid"><div><p>Integrated services</p><h3 className="display"><Counter value={6}/></h3></div><div><p>Regions of Ghana covered</p><h3 className="display"><Counter value={16}/></h3></div><div><p>Emergency response desk</p><h3 className="display"><Counter value={24} suffix="/7"/></h3></div><div><p>Seaports coordinated</p><h3 className="display"><Counter value={2}/></h3></div></div></section>

<section className="cta-band"><div className="container"><h2 className="display">YOUR NEXT MOVEMENT STARTS WITH A CLEAR CONVERSATION.</h2><a className="btn btn-primary" href={wa("Hi Avar, I'd like to discuss a logistics requirement.")} target="_blank">Message an agent <ArrowRight size={16}/></a></div></section></main>}
