export const phone = '233243332016'; // Primary line (calls & WhatsApp)
export const emergencyPhone = '+233 24 333 2016';
export const phone2 = '+233 20 552 1051';
export const email = 'info@avarlogisticsafrica.com';
export const siteUrl = 'https://avarlogisticsafricaltd.com';
export const wa = (message:string) => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

export type Service = {slug:string; title:string; short:string; eyebrow:string; intro:string; image:string; points:string[]; meta:string};
export const services:Service[] = [
 {slug:'car-rental',title:'Car Rental',eyebrow:'Self-drive & chauffeured rentals',short:'Well-maintained vehicles for daily, weekly or long-term rental — self-drive or with a professional driver.',intro:'Rent with confidence from a fleet that is inspected, insured and prepared before every handover, with flexible terms for individuals and organisations.',image:'/images/car-rental.jpg',points:['Self-drive and chauffeured options','Daily, weekly and long-term lease terms','Inspected, insured and delivery-ready vehicles'],meta:'Car rental Ghana | Self drive & chauffeured | Avar Logistics'},
 {slug:'vehicle-importation',title:'Vehicle Importation',eyebrow:'Door-to-door vehicle logistics',short:'A controlled import process from overseas purchase to handover in Ghana.',intro:'Import with a team that keeps documentation, port coordination and vehicle movement under one accountable process.',image:'/images/vehicle-import.jpg',points:['Pre-shipment guidance and documentation review','Port handling and clearing coordination','Secure onward delivery and handover'],meta:'Car importation Ghana | Avar Logistics Africa'},
 {slug:'distribution',title:'Distribution of Goods',eyebrow:'Regional distribution',short:'Planned, trackable movement of products across Ghana and the sub-region.',intro:'From recurring retail drops to project deliveries, we align routes, handling and reporting with your operating requirements.',image:'/images/hero-fleet.jpg',points:['Route and delivery-window planning','Proof-of-delivery reporting','Dedicated enterprise coordination'],meta:'Goods distribution company Ghana | Avar Logistics'},
 {slug:'staff-bussing',title:'Staff Bussing',eyebrow:'Reliable employee shuttles',short:'Scheduled company bussing that gets your people to work safely and on time, every day.',intro:'We run dependable staff shuttle services for companies and institutions — planned routes, vetted drivers and consistent daily timing your teams can build their day around.',image:'/images/staff-bussing.jpg',points:['Scheduled pick-up and drop-off routes','Vetted, professional drivers','Route planning around shifts and sites'],meta:'Staff bussing Ghana | Company shuttle service Accra'},
 {slug:'private-vip-drive',title:'Private / VIP Drive',eyebrow:'Discreet executive mobility',short:'Professional vehicles and drivers for executives, delegations and private clients.',intro:'Move your teams and guests with punctual, discreet professional transport planned around itinerary, protocol and security needs.',image:'/images/vip-transport.jpg',points:['Professional chauffeur and private hire drivers','Airport, event and delegation movements','Optional police escort coordination'],meta:'VIP transport Ghana | Private driver Accra | Avar Logistics'}
];
