export const phone = '233000000000'; // Replace with ALAL's verified WhatsApp number
export const emergencyPhone = '+233 (0) 00 000 0000'; // Placeholder: client confirmation required
export const wa = (message:string) => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

export type Service = {slug:string; title:string; short:string; eyebrow:string; intro:string; image:string; points:string[]; meta:string};
export const services:Service[] = [
 {slug:'vehicle-importation',title:'Vehicle Importation',eyebrow:'Door-to-door vehicle logistics',short:'A controlled import process from overseas purchase to handover in Ghana.',intro:'Import with a team that keeps documentation, port coordination and vehicle movement under one accountable process.',image:'/images/port-operations.jpg',points:['Pre-shipment guidance and documentation review','Port handling and clearing coordination','Secure onward delivery and handover'],meta:'Car importation Ghana | Avar Logistics Africa'},
 {slug:'distribution',title:'Distribution of Goods',eyebrow:'Regional distribution',short:'Planned, trackable movement of products across Ghana and the sub-region.',intro:'From recurring retail drops to project cargo, we align routes, handling and reporting with your operating requirements.',image:'/images/hero-fleet.jpg',points:['Route and delivery-window planning','Proof-of-delivery reporting','Dedicated enterprise coordination'],meta:'Goods distribution company Ghana | Avar Logistics'},
 {slug:'car-rental-vip-transport',title:'Car Rental & VIP Transport',eyebrow:'Discreet executive mobility',short:'Professional vehicles and drivers for executives, delegations and events.',intro:'Move principals and guests with punctual, discreet ground transport planned around itinerary, protocol and security needs.',image:'/images/vip-transport.jpg',points:['Professional chauffeur service','Airport, event and delegation movements','Optional police escort coordination'],meta:'VIP transport Ghana | Executive car rental Accra'},
 {slug:'clearing-of-goods',title:'Clearing of Goods',eyebrow:'Port and customs support',short:'Clear documentation, active coordination and responsible cargo handling.',intro:'Reduce uncertainty at the port with a clearing team that communicates requirements early and keeps your consignment moving.',image:'/images/port-operations.jpg',points:['Document readiness review','Customs and terminal coordination','Collection and onward transport'],meta:'Clearing agent Ghana | Goods clearing Tema Port'},
 {slug:'packaging-labeling',title:'Packaging & Labeling',eyebrow:'Prepared for safe movement',short:'Consistent packaging and labeling for storage, distribution and delivery.',intro:'Protect product integrity and improve handling accuracy with packaging workflows designed around your goods and destination.',image:'/images/warehouse-team.jpg',points:['Product-specific packing plans','Batch and destination labeling','Dispatch-ready quality checks'],meta:'Packaging and labeling services Ghana'},
 {slug:'warehouse-management',title:'Warehouse Management',eyebrow:'Control at every touchpoint',short:'Structured receiving, storage, picking and dispatch operations.',intro:'Maintain visibility and discipline across inventory movement with professional warehouse processes and accountable teams.',image:'/images/warehouse-team.jpg',points:['Receiving and inventory controls','Pick, pack and dispatch workflows','Operational reporting'],meta:'Warehouse management Ghana | Logistics services'},
 {slug:'general-trading',title:'General Trading',eyebrow:'Responsible commercial sourcing',short:'Practical procurement and supply support for organisations and projects.',intro:'We help organisations source and move goods with disciplined supplier coordination and logistics support.',image:'/images/warehouse-team.jpg',points:['Supplier and order coordination','Transport and delivery planning','Business and project supply support'],meta:'General trading and logistics Ghana'}
];
